### ISSUE TITLE
Circular dependency error with "stream-browserify"

### ISSUE THREAD

**Issue by adioo** [cramforce/splittable#16]
Following error occurs, when *splittable* tries to bundle [stream-browserify](https://github.com/substack/stream-browserify):
```sh
AssertionError: Node node_modules/readable-stream/lib/_stream_duplex.js forms circular dependency: node_modules/readable-stream/writable.js -> node_modules/readable-stream/lib/_stream_writable.js -> node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_readable.js -> node_modules/readable-stream/lib/_stream_duplex.js
    at TopologicalSort._exploreNode (/test/node_modules/topological-sort/build.js:63:13)
    at TopologicalSort._exploreNode (/test/node_modules/topological-sort/build.js:80:18)
    at TopologicalSort._exploreNode (/test/node_modules/topological-sort/build.js:80:18)
    at TopologicalSort._exploreNode (/test/node_modules/topological-sort/build.js:80:18)
    at TopologicalSort._exploreNode (/test/node_modules/topological-sort/build.js:80:18)
    at TopologicalSort.sort (/test/node_modules/topological-sort/build.js:48:18)
    at Readable.<anonymous> (/test/node_modules/splittable/splittable.js:205:36)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (/test/node_modules/readable-stream/lib/_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
The error is thrown [here](https://github.com/1999/topological-sort/blob/53bf887f476eb6eb233d6b8c38e547918f9c6567/index.js#L55).  

How I got the error:
```sh
mkdir test/
mkdir test/bundles/
cd test/
npm install splittable
npm install stream-browserify
```
```js
// bundle.js
"use strict";

const splittable = require("splittable");

splittable({
    modules: ['./module.js'],
    out: './bundles'
}).then(
    (info) => {console.log('Warn:', info);},
    (reason) => {console.log('Error:', reason)}
);
```
```js
// modules.js
"use strict";
const Readable = require("stream-browserify").readable;
```
Then call:
```sh
node bundle.js
```
It would be super cool, if *splittable* can handle circular dependencies 👍. I'm not really experienced with dependency tree parsing, but it should be possible, right?
Thanks for this awesome module!

**Comment by cramforce** [comment]
While it would be possible to handle some cases of circular CommonJS deps,
it would be a backward incompatible change to closure compiler. I think it
is unlikely to happen given that ES6 modules do not support it.

**Comment by cramforce** [comment]
That and things would fail randomly when modules get put into different
bundles because of the implicit circular dep.

**Comment by adioo** [comment]
Ok, I see. So, CommonJS modules need to "fix" their circular dependencies, in order to be transpiled to ES6 modules.
